Bag of Words (BoW)
BoW represents text as a fixed-length vector of word counts, ignoring grammar and word order.

How it works
1. Build a vocabulary
Collect all unique words across your entire corpus:


"the cat sat" + "the dog ran" → vocabulary: {the, cat, sat, dog, ran}
2. Vectorize each document
Count how many times each vocabulary word appears in each document:

Document	the	cat	sat	dog	ran
"the cat sat"	1	1	1	0	0
"the dog ran"	1	0	0	1	1
3. Use vectors for ML tasks
These vectors become features for classification, clustering, similarity, etc.

Variants
Binary BoW — 1 if word present, 0 if not (ignores frequency)
TF-IDF — weights counts by how rare a word is across documents (penalizes "the", boosts "serendipity")
N-gram BoW — treats word pairs/triples as tokens ("not good" vs "not" + "good")
Key limitations
Loses word order — "dog bites man" == "man bites dog"
Sparse, high-dimensional vectors — large vocabularies make huge mostly-zero matrices
No semantic meaning — "car" and "automobile" are unrelated in BoW
This is why word embeddings (Word2Vec, GloVe) and transformer models (BERT) were developed — they capture meaning and context that BoW discards.

In [8]:
import numpy as np
def bag_of_words(sentences):
    """
    Creates a bag of words represnetation of a list of documents
    """
    tokenized_sentences = [
        sentence.lower().split() for sentence in sentences
    ]
    flat_words =[
        word for sublist in tokenized_sentences for word in sublist
    ]
    vocabulary = sorted(set(flat_words))
    word_to_index ={word: i for i, word in enumerate(vocabulary)}

    bow_matrix = np.zeros((
        len(sentences), len(vocabulary)), dtype=int)
    for i, sentence in enumerate(tokenized_sentences):
        for word in sentence:
            if word in word_to_index:
                bow_matrix[i, word_to_index[word]] +1
    return vocabulary, bow_matrix

In [9]:
corpus =["This movie is awesom",
        "I do not say is good, but neither awesom",
        "Awesome, only a fool can say that"]
vocabulary, bow_matrix = bag_of_words(corpus)
print("Vocabulary", vocabulary)
print("Bag of words Matrix:\n", bow_matrix)

Vocabulary ['a', 'awesom', 'awesome,', 'but', 'can', 'do', 'fool', 'good,', 'i', 'is', 'movie', 'neither', 'not', 'only', 'say', 'that', 'this']
Bag of words Matrix:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


Code Summary
This function converts a list of sentences into a numeric matrix representation.

Steps:

Tokenize — lowercases and splits each sentence into words
Build vocabulary — collects all unique words, sorts them, and assigns each an index
Build matrix — creates a (num_sentences × vocab_size) zero matrix, then increments the count for each word found in each sentence
Returns: the vocabulary list and the count matrix

Bug on line 19: bow_matrix[i, word_to_index[word]] +1 computes but never assigns — the matrix stays all zeros. Fix:


bow_matrix[i, word_to_index[word]] += 1